### ISSUE TITLE
Release annotations: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by marefr** [grafana/devtools#25]
Problem with release annotation projection.

```
2021-03-22 04:17:55	
Aggregator Running 1616386675
2021-03-22 04:17:26	
	/home/marcus/go/src/github.com/grafana/devtools/pkg/streams/memorybus/memory_bus.go:83 +0x1dd
2021-03-22 04:17:26	
created by github.com/grafana/devtools/pkg/streams/memorybus.(*InMemoryBus).Start.func1
2021-03-22 04:17:26	
	/home/marcus/go/src/github.com/grafana/devtools/pkg/streams/memorybus/memory_bus.go:84 +0x51
2021-03-22 04:17:26	
github.com/grafana/devtools/pkg/streams/memorybus.(*InMemoryBus).Start.func1.1(0xc0002b5740, 0xc0001ea000, 0xc0368d2d20, 0xc00e2475a3ac8622, 0x4e0fede75c, 0x10a41a0, 0xc00002d330)
2021-03-22 04:17:26	
	/home/marcus/go/src/github.com/grafana/devtools/pkg/streams/projections/engine.go:95 +0x1b4
2021-03-22 04:17:26	
github.com/grafana/devtools/pkg/streams/projections.(*StreamProjection).createSubscriber.func1(0xadc320, 0xc0001ea000, 0xc0368d2d20)
2021-03-22 04:17:26	
	/home/marcus/go/src/github.com/grafana/devtools/pkg/streams/projections/partitioning.go:45 +0x170
2021-03-22 04:17:26	
github.com/grafana/devtools/pkg/streams/projections.(*partionedProjection).Run(0xc00019bbf0, 0xc0368d2d20, 0x1c, 0xc036677280, 0x2)
2021-03-22 04:17:26	
	/home/marcus/go/src/github.com/grafana/devtools/pkg/streams/projections/projection.go:67 +0x35b
2021-03-22 04:17:26	
github.com/grafana/devtools/pkg/streams/projections.(*projection).callApply(0xc0001a53e0, 0x95f5a0, 0xc0284c2cc0, 0x9bd280, 0xc03b801f20, 0x0, 0x0, 0x0)
2021-03-22 04:17:26	
	/usr/local/go/src/reflect/value.go:308 +0xa4
2021-03-22 04:17:26	
reflect.Value.Call(0x984820, 0xc0001a97a0, 0x13, 0xc0293825a0, 0x2, 0x2, 0x1, 0x2, 0xc03cd5cc78)
2021-03-22 04:17:26	
	/usr/local/go/src/reflect/value.go:447 +0x461
2021-03-22 04:17:26	
reflect.Value.call(0x984820, 0xc0001a97a0, 0x13, 0xa23a30, 0x4, 0xc0293825a0, 0x2, 0x2, 0x2, 0xc0293825a0, ...)
2021-03-22 04:17:26	
	/home/marcus/go/src/github.com/grafana/devtools/pkg/githubstats/release_annotation.go:49 +0x93
2021-03-22 04:17:26	
github.com/grafana/devtools/pkg/githubstats.(*ReleaseAnnotationProjections).apply(0xc0001ac1b8, 0xc0284c2cc0, 0xc03b801f20)
2021-03-22 04:17:26	
goroutine 336 [running]:
2021-03-22 04:17:26	

2021-03-22 04:17:26	
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x87c523]
2021-03-22 04:17:26	
panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by marefr** [comment]
Fixed by #26
